const express = require('express')
    //中间件自定义
const postLogin = require('./admin/postLogin')
const loginOUt=require('./admin/loginOut')
const getUser = require('./admin/getUser')
const getLogin = require('./admin/getLogin')
const getEdit = require('./admin/getEdit')
const postAdd = require('./admin/postAdd')
const postEdit = require('./admin/postEdit')
const getDelete = require('./admin/getDelete')
const articles = require('./admin/articles')
const articleEdit = require('./admin/articleEdit')
const articleAdd = require('./admin/articleAdd')
const { user } = require('../model/users')
    // const app=express()
const admin = express.Router()

admin.get('/login', getLogin)
admin.get('/user', getUser)
admin.post('/login', postLogin)
admin.get('/loginOUt',loginOUt)
admin.get('/userEdit', getEdit)
admin.get('/delete', getDelete)
admin.post('/userEdit', postEdit)
admin.post('/userAdd', postAdd)

admin.get('/article', articles)
admin.get('/articleEdit', articleEdit)
admin.post('/articleAdd', articleAdd)
module.exports = admin;